# nome da pipeline
name: Run basic testes
#em que momento será executada
on:
  pull_request:
    branches: [master]

jobs:
  # o que vai ser feito nessa pipeline, teremos somente um job: rodar os testes
  cypress-run:
  #maquina que será executado
    runs-on: ubuntu-latest 
    # passo a passo para rodar os tests
    steps:
      #clone do projeto
      - name: Checkout/Clone do projeto
        uses:  actions/checkout@v4
      #Exemplo de excução no terminal
      - name: Executar comando do terminal
        uses: echo Andre Cassaniga
      #execução e config do projeto
      - name: Run testes
        uses: cypress-io/github-action@v6
        whith:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}